<a href="https://colab.research.google.com/github/ALOKDUBEYFORU/ALOKDUBEYFORU/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import the numpy module with the alias name as np.
import numpy as np
import time

In [3]:
#Measuring the time delay in performing an operation with list than that of numpy array.
#Creating the list variable to store the number from 1 to 1000000.
list1 = list(range(1000000))
#creating a numpy arrange varaible to store the numbers from 1 to 1000000
arr1 = np.arange(1000000)

#measuring the time delay of doing the sum of all the elements of the list
start = time.time()
sum_list1 = sum(list1)
end = time.time()
time_delay_list = end - start

#measuring the time delay of doing the sum of all the elements of the numpy array
start = time.time()
sum_arr1 = np.sum(arr1)
end = time.time()
time_delay_arr = end - start

print('time taken by the list :',time_delay_list)
print('time taken by the array :',time_delay_arr)


time taken by the list : 0.014433860778808594
time taken by the array : 0.0012888908386230469


#Outcome :
*     Numpy is approximately 9 times faster than the list.

In [10]:
#declaration of an array in 1d, 2d, 3d
#1d array
arr_1_d = np.array([1,2,3])
#2d array
arr_2_d = np.array([[1,2,3],[4,5,6]])
#3d array
arr_3_d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print('1d array :\n',arr_1_d)
print('\n2d array :\n',arr_2_d)
print('\n3d array :\n',arr_3_d)

1d array :
 [1 2 3]

2d array :
 [[1 2 3]
 [4 5 6]]

3d array :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
#ndim : used to find out the number of dimension of an array
print('dimension of 1d array ',arr_1_d.ndim )
print('dimension of 2d array ',arr_2_d.ndim )
print('dimension of 3d array ',arr_3_d.ndim )

dimension of 1d array  1
dimension of 2d array  2
dimension of 3d array  3


In [13]:
#shape method is used to idenfity the shape of the array.
print('shape of 1d array ',arr_1_d.shape )
print('shape of 2d array ',arr_2_d.shape )
print('shape of 3d array ',arr_3_d.shape )

shape of 1d array  (3,)
shape of 2d array  (2, 3)
shape of 3d array  (2, 2, 3)


#Outcome :


*   shape method of 1d array returns the number of elements in it in a tuple format.
*   shape method of 2d array returns the number of rows and columns of in the array. There are two rows and three columns in the 2d array.
*   shape method of 3d array returns the number of elements in the first dimension, 2nd dimension and third dimension. second dimension represents the rows, third dimension represents the columns


In [14]:
#size method is used to identify the number of elements in an array. This can be multiplication of values returned by shape method as well.
print('shape of 1d array ',arr_1_d.size )
print('shape of 2d array ',arr_2_d.size )
print('shape of 3d array ',arr_3_d.size )

shape of 1d array  3
shape of 2d array  6
shape of 3d array  12


In [16]:
#storing a mixed data into a numpy array
arr1 = np.array([10,100.0,'python'])
print(arr1)

arr2 = np.array([10,100.0])
print(arr2)


['10' '100.0' 'python']
[ 10. 100.]


#Outcome for a mixed data in a numpy array :
*    if we store an integer, decimal and a string in a numpy array, then it will convert all the elements into string format
*    If we store an integer, floating number in a numpy array, then it will conver the integer into a floating number.