<a href="https://colab.research.google.com/github/ALOKDUBEYFORU/ALOKDUBEYFORU/blob/main/Question1_paper_on_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	Create a 1D NumPy array of numbers from 0 to 19 using arange. What is the shape and number of dimensions?
2.	Convert the following float array to integer using astype:
arr = np.array([1.2, 3.5, 4.9])
3.	Index the value at 2nd row and 3rd column from the following array:
a = np.array([[10, 20, 30], [40, 50, 60]])
4.	Slice every second value from the array:
b = np.arange(10, 30)
5.	Transpose a 2x3 matrix and print its shape before and after:
arr = np.array([[1, 2, 3], [4, 5, 6]])
6.	Reshape a 1D array of 20 elements into a 2D array with 4 rows. What is the shape?
7.	Given a 2D array of shape (4, 5), replace all even numbers with 0 using where.
8.	Use fancy indexing to extract the 1st, 3rd, and 4th rows from the following array:
data = np.arange(40).reshape(5, 8)
9.	Given a 2D array, find the sum of each column using an aggregate function.
10.	Use broadcasting to subtract the column means from a 2D array (zero-center each column).
11.	Check if all values in a row are greater than 0 using all across axis=1:
arr = np.array([[1, 2, 3], [0, 4, 5]])
12.	Check if any value in each column is negative using any across axis=0:
arr = np.array([[1, -1], [3, 4]])
13.	Create a 5x5 matrix using arange, and extract the diagonal using slicing.
14.	Use astype to convert a matrix of floats to uint8 and explain what happens if a value > 255 exists.
15.	Given a 2D array, replace all values > 50 with 99 using where.



In [1]:
import numpy as np

In [2]:
#1. Create a 1D NumPy array of numbers from 0 to 19 using arange. What is the shape and number of dimensions?
arr1 = np.arange(0,20)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
#2. Convert the following float array to integer using astype: arr = np.array([1.2, 3.5, 4.9])

arr = np.array([1.2, 3.5, 4.9])

arr = arr.astype(int)
print(arr)

[1 3 4]


In [5]:
#3. Index the value at 2nd row and 3rd column from the following array: a = np.array([[10, 20, 30], [40, 50, 60]])
a = np.array([[10, 20, 30], [40, 50, 60]])
print(a[1,2])

60


In [6]:
#4. Slice every second value from the array: b = np.arange(10, 30)

b = np.arange(10, 30)
print(b[::2])

[10 12 14 16 18 20 22 24 26 28]


In [7]:
#5. Transpose a 2x3 matrix and print its shape before and after: arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('array before transose :\n',arr)
print('array after transose :\n',arr.T)

array before transose :
 [[1 2 3]
 [4 5 6]]
array after transose :
 [[1 4]
 [2 5]
 [3 6]]


In [8]:
#6. Reshape a 1D array of 20 elements into a 2D array with 4 rows. What is the shape?

arr = np.arange(1,21)
print(arr.reshape(4,-1).shape)

(4, 5)


In [11]:
# 7. Given a 2D array of shape (4, 5), replace all even numbers with 0 using where.

arr = np.arange(1,21).reshape(4,5)
arr = np.where(arr%2==0,0,arr)
print(arr)

arr = np.arange(1,21).reshape(4,5)
arr[arr%2 == 0] = 0
print(arr)

[[ 1  0  3  0  5]
 [ 0  7  0  9  0]
 [11  0 13  0 15]
 [ 0 17  0 19  0]]
[[ 1  0  3  0  5]
 [ 0  7  0  9  0]
 [11  0 13  0 15]
 [ 0 17  0 19  0]]


In [13]:
#8. Use fancy indexing to extract the 1st, 3rd, and 4th rows from the following array: data = np.arange(40).reshape(5, 8)

data = np.arange(40).reshape(5, 8)
print(data)
print(data[[1,3,4],:])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]
[[ 8  9 10 11 12 13 14 15]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [14]:
# 9. Given a 2D array, find the sum of each column using an aggregate function.
arr = np.arange(20).reshape(4,5)
print(arr)
print(np.sum(arr,axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]


In [20]:
# 10. Use broadcasting to subtract the column means from a 2D array (zero-center each column).

arr = np.arange(-10,10).reshape(5,4)
print(arr)
print(arr - np.average(arr,axis=0))

[[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]
 [  6   7   8   9]]
[[-8. -8. -8. -8.]
 [-4. -4. -4. -4.]
 [ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]
 [ 8.  8.  8.  8.]]


In [21]:
# 11. Check if all values in a row are greater than 0 using all across axis=1: arr = np.array([[1, 2, 3], [0, 4, 5]])
arr = np.array([[1, 2, 3], [0, 4, 5]])
print(np.all(arr>0,axis=1))

[ True False]


In [22]:
# 12. Check if any value in each column is negative using any across axis=0: arr = np.array([[1, -1], [3, 4]])

arr = np.array([[1, -1], [3, 4]])
print(np.any(arr < 0, axis = 0))

[False  True]


In [27]:
#13. Create a 5x5 matrix using arange, and extract the diagonal using slicing.
arr = np.arange(25).reshape(5,5)
print(arr)
print(arr[np.arange(0,5),np.arange(0,5)])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  6 12 18 24]


In [31]:
#14. Use astype to convert a matrix of floats to uint8 and explain what happens if a value > 255 exists.
arr = np.arange(250,260,dtype = float)
print(arr.astype('uint8'))

[250 251 252 253 254 255   0   1   2   3]


In [32]:
#15. Given a 2D array, replace all values > 50 with 99 using where.
arr = np.arange(40,60).reshape(4,5)
print(arr)
print(np.where(arr>50,99,arr))

[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 99 99 99 99]
 [99 99 99 99 99]]
